"use client";

import { AlertCircle, CheckCircle2, Lightbulb } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { ResumeFeedback } from "@/lib/types";

export function FeedbackPanel({ feedback }: { feedback: ResumeFeedback }) {
  return (
    <div className="flex flex-col gap-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-base">AI Resume Feedback</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-2">
          <p className="text-sm leading-relaxed text-muted">{feedback.overall_summary}</p>
          <span className="text-xs text-muted">Generated by: {feedback.provider}</span>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-sm">
              <CheckCircle2 className="h-4 w-4 text-success" /> Strengths
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-1.5 text-sm text-muted">
            {feedback.strengths.length ? (
              feedback.strengths.map((s) => <span key={s}>• {s}</span>)
            ) : (
              <span>No notable strengths detected yet.</span>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-sm">
              <AlertCircle className="h-4 w-4 text-warning" /> Missing sections
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-1.5">
            {feedback.missing_sections.length ? (
              feedback.missing_sections.map((s) => (
                <Badge key={s} tone="warning">
                  {s}
                </Badge>
              ))
            ) : (
              <span className="text-sm text-muted">Nothing major missing. 🎉</span>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-sm">
              <Lightbulb className="h-4 w-4 text-primary" /> Suggestions
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-1.5 text-sm text-muted">
            {feedback.suggestions.map((s) => (
              <span key={s}>• {s}</span>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
